// Reelify Movie Database - Extended with trailers, IMDB, AI reviews
const MOVIES = [
    { id: 1, title: "Esaretin Bedeli", year: 1994, duration: 142, rating: 9.3, imdb: 9.3, poster: "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=6hB3S9bIaco", genres: ["Dram", "Suç"], overview: "Bankacı Andy Dufresne, işlemediği bir suç yüzünden ömür boyu hapse mahkum edilir.", platforms: ["Netflix", "Amazon Prime"], keywords: ["umut", "dostluk", "özgürlük", "ağlatıcı", "düşündürücü", "klasik"], pros: ["Mükemmel oyunculuklar", "Unutulmaz hikaye", "Derin mesajlar"], cons: ["Yavaş tempo bazıları için sıkıcı olabilir"], spoiler: "Andy tüneli kazarak kaçar ve özgürlüğüne kavuşur." },
    { id: 2, title: "Baba", year: 1972, duration: 175, rating: 9.2, imdb: 9.2, poster: "https://m.media-amazon.com/images/M/MV5BYTJkNGQyZDgtZDQ0NC00MDM0LWEzZWQtYzUzZDEwMDljZWNjXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BYTJkNGQyZDgtZDQ0NC00MDM0LWEzZWQtYzUzZDEwMDljZWNjXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=sY1S34973zA", genres: ["Suç", "Dram"], overview: "Corleone ailesinin patriarkı Don Vito, suç imparatorluğunu oğluna devreder.", platforms: ["Netflix", "BluTV"], keywords: ["mafya", "aile", "güç", "klasik", "efsane", "düşündürücü"], pros: ["Sinema tarihinin en iyi filmi", "Brando efsanevi"], cons: ["Uzun süre", "Şiddet içerir"], spoiler: "Michael babasının yerini alır ve tüm düşmanlarını öldürür." },
    { id: 3, title: "Kara Şövalye", year: 2008, duration: 152, rating: 9.0, imdb: 9.0, poster: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY", genres: ["Aksiyon", "Suç"], overview: "Batman, Gotham'ı terörize eden Joker'e karşı mücadele eder.", platforms: ["Netflix", "HBO Max"], keywords: ["süper kahraman", "aksiyon", "gerilim", "batman", "joker", "karanlık"], pros: ["Heath Ledger'ın Joker'i efsane", "Görsel şölen"], cons: ["Karanlık ton herkes için değil"], spoiler: "Joker yakalanır ama Harvey Dent kötüye döner." },
    { id: 4, title: "Forrest Gump", year: 1994, duration: 142, rating: 8.8, imdb: 8.8, poster: "https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=bLvqoHBptjg", genres: ["Dram", "Romantik"], overview: "Düşük IQ'lu ama büyük kalpli Forrest'ın olağanüstü yaşam hikayesi.", platforms: ["Amazon Prime", "Disney+"], keywords: ["ağlatıcı", "ilham", "nostaljik", "romantik", "dram", "klasik"], pros: ["Tom Hanks muhteşem", "Duygusal yolculuk"], cons: ["Politik mesajlar tartışmalı"], spoiler: "Jenny ölür, Forrest oğluyla kalır." },
    { id: 5, title: "Inception", year: 2010, duration: 148, rating: 8.8, imdb: 8.8, poster: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0", genres: ["Bilim Kurgu", "Aksiyon"], overview: "Dom Cobb, insanların rüyalarına girerek düşüncelerini çalabilen bir hırsızdır.", platforms: ["Netflix", "HBO Max"], keywords: ["bilim kurgu", "rüya", "aksiyon", "karmaşık", "düşündürücü", "nolan"], pros: ["Orijinal konsept", "Görsel efektler muhteşem"], cons: ["Karmaşık olabilir"], spoiler: "Totem dönmeye devam eder, gerçeklik belirsiz." },
    { id: 6, title: "Yıldızlararası", year: 2014, duration: 169, rating: 8.7, imdb: 8.7, poster: "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=zSWdZVtXT7E", genres: ["Bilim Kurgu", "Dram"], overview: "Astronotlar insanlık için yeni bir yuva bulmak üzere galaksiler ötesine yolculuk yapar.", platforms: ["Netflix", "Amazon Prime"], keywords: ["bilim kurgu", "uzay", "duygusal", "epik", "baba", "aile", "nolan"], pros: ["Görsel şölen", "Duygusal derinlik"], cons: ["Bilimsel detaylar karmaşık"], spoiler: "Cooper kara delikten geçer ve kızıyla iletişim kurar." },
    { id: 7, title: "Dövüş Kulübü", year: 1999, duration: 139, rating: 8.8, imdb: 8.8, poster: "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=SUXWAEX2jlg", genres: ["Dram", "Gerilim"], overview: "Uykusuzluktan mustarip bir adam, Tyler Durden ile tanışır ve dövüş kulüpleri kurar.", platforms: ["Amazon Prime"], keywords: ["kült", "psikolojik", "twist", "karanlık", "düşündürücü", "farklı"], pros: ["Twist efsanevi", "Brad Pitt muhteşem"], cons: ["Şiddet içerir"], spoiler: "Tyler Durden aslında anlatıcının ikinci kişiliği." },
    { id: 8, title: "Matrix", year: 1999, duration: 136, rating: 8.7, imdb: 8.7, poster: "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=vKQi3bBA1y8", genres: ["Bilim Kurgu", "Aksiyon"], overview: "Neo, gerçekliğin makineler tarafından yaratılmış bir simülasyon olduğunu keşfeder.", platforms: ["Netflix", "HBO Max"], keywords: ["bilim kurgu", "aksiyon", "felsefe", "klasik", "devrimci"], pros: ["Devrimci görsel efektler", "Derin felsefe"], cons: ["Devam filmleri hayal kırıklığı"], spoiler: "Neo Seçilmiş Kişi olduğunu kabul eder ve Matrix'i kontrol eder." },
    { id: 9, title: "Yeşil Yol", year: 1999, duration: 189, rating: 8.6, imdb: 8.6, poster: "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2MDY3._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2MDY3._V1_.jpg", trailer: "https://www.youtube.com/watch?v=Ki4haFrqSrw", genres: ["Dram", "Fantastik"], overview: "İdam koğuşunda mucizevi güçlere sahip bir mahkumla tanışan gardiyanın hikayesi.", platforms: ["Netflix", "Amazon Prime"], keywords: ["ağlatıcı", "duygusal", "dram", "fantastik", "mucize", "düşündürücü"], pros: ["Çok duygusal", "Michael Clarke Duncan efsane"], cons: ["3 saat uzun"], spoiler: "John Coffey masum olmasına rağmen idam edilir." },
    { id: 10, title: "Titanik", year: 1997, duration: 194, rating: 7.9, imdb: 7.9, poster: "https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=kVrqfYjkTdQ", genres: ["Romantik", "Dram"], overview: "Batan efsanevi gemide zengin Rose ve fakir Jack arasındaki aşk hikayesi.", platforms: ["Disney+", "Amazon Prime"], keywords: ["romantik", "ağlatıcı", "aşk", "epik", "klasik", "trajik"], pros: ["Görsel şölen", "Romantik klasik"], cons: ["Çok uzun"], spoiler: "Jack donarak ölür, Rose hayatta kalır." },
    { id: 11, title: "Joker", year: 2019, duration: 122, rating: 8.4, imdb: 8.4, poster: "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=zAGVQLHvwOY", genres: ["Suç", "Dram"], overview: "Arthur Fleck'in toplum tarafından dışlanan bir adamdan Joker'e dönüşümü.", platforms: ["Netflix", "HBO Max"], keywords: ["karanlık", "psikolojik", "dram", "düşündürücü", "yalnızlık"], pros: ["Joaquin Phoenix Oscar'lık", "Görsel sanat eseri"], cons: ["Çok karanlık ve ağır"], spoiler: "Arthur canlı yayında sunucuyu öldürür." },
    { id: 12, title: "Parasit", year: 2019, duration: 132, rating: 8.5, imdb: 8.5, poster: "https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=5xH0HfJHsaY", genres: ["Gerilim", "Dram"], overview: "Yoksul Ki-taek ailesi, zengin Park ailesinin evine sızar.", platforms: ["Netflix", "Amazon Prime"], keywords: ["kore", "gerilim", "sınıf farkı", "twist", "oscar", "farklı"], pros: ["Oscar kazandı", "Beklenmedik hikaye"], cons: ["Şiddet sahneleri var"], spoiler: "Bodrumdaki adam ortaya çıkar ve kaos başlar." },
    { id: 13, title: "Whiplash", year: 2014, duration: 106, rating: 8.5, imdb: 8.5, poster: "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=7d_jQycdQGo", genres: ["Dram", "Müzik"], overview: "Genç davulcu, acımasız müzik öğretmeni Fletcher'ın rehberliğinde mükemmelliğe ulaşmaya çalışır.", platforms: ["Netflix", "Amazon Prime"], keywords: ["müzik", "yoğun", "gerilim", "tutku", "mükemmellik"], pros: ["JK Simmons Oscar'lık", "Müzik muhteşem"], cons: ["Stresli izleme deneyimi"], spoiler: "Andrew final performansında Fletcher'ı alt eder." },
    { id: 14, title: "Amélie", year: 2001, duration: 122, rating: 8.3, imdb: 8.3, poster: "https://m.media-amazon.com/images/M/MV5BNDg4NjM1YjMtYmNhZC00MjM0LWFiZmYtNGY1YjA3MzZmODc5XkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BNDg4NjM1YjMtYmNhZC00MjM0LWFiZmYtNGY1YjA3MzZmODc5XkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=HUECWi5pX7o", genres: ["Romantik", "Komedi"], overview: "Paris'te yaşayan utangaç Amélie, etrafındaki insanların hayatlarını gizlice iyileştirir.", platforms: ["Netflix", "MUBI"], keywords: ["romantik", "mutlu", "renkli", "büyülü", "paris", "sevimli"], pros: ["Görsel olarak büyüleyici", "Sıcacık his"], cons: ["Yavaş tempo"], spoiler: "Amélie sonunda Nino'yu bulur ve mutlu olur." },
    { id: 15, title: "Gladyatör", year: 2000, duration: 155, rating: 8.5, imdb: 8.5, poster: "https://m.media-amazon.com/images/M/MV5BYWQ4YmNjYjEtOWE1Zi00Y2U4LWI4NTAtMTU0MjkxNWQ1ZmJiXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BYWQ4YmNjYjEtOWE1Zi00Y2U4LWI4NTAtMTU0MjkxNWQ1ZmJiXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=owK1qxDselE", genres: ["Aksiyon", "Dram"], overview: "Roma generali Maximus, ihanete uğrar ve gladyatör olarak intikam peşinde koşar.", platforms: ["Netflix", "Amazon Prime"], keywords: ["epik", "aksiyon", "intikam", "roma", "savaş", "kahraman"], pros: ["Russell Crowe muhteşem", "Epik savaş sahneleri"], cons: ["Şiddet içerir"], spoiler: "Maximus Commodus'u öldürür ama kendisi de ölür." },
    { id: 16, title: "Korku Seansı", year: 2013, duration: 112, rating: 7.5, imdb: 7.5, poster: "https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=k10ETZ41q5o", genres: ["Korku", "Gerilim"], overview: "Paranormal araştırmacılar bir çiftlik evindeki ürkütücü olayları araştırır.", platforms: ["Netflix", "HBO Max"], keywords: ["korku", "gerilim", "hayalet", "paranormal", "ürkütücü"], pros: ["Gerçekten korkutucu", "Atmosfer mükemmel"], cons: ["Klişe korku unsurları"], spoiler: "Annette'in üzerindeki lanet kaldırılır." },
    { id: 17, title: "Hachi", year: 2009, duration: 93, rating: 8.1, imdb: 8.1, poster: "https://m.media-amazon.com/images/M/MV5BNzE4NDg5OWMtMzg3NC00ZDRjLTllMDMtZTRjNWZmNjBmMGZlXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BNzE4NDg5OWMtMzg3NC00ZDRjLTllMDMtZTRjNWZmNjBmMGZlXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=bRxfrdBHmBc", genres: ["Dram", "Aile"], overview: "Bir köpeğin sahibine olan sonsuz sadakatinin gerçek hikayesi.", platforms: ["Amazon Prime"], keywords: ["ağlatıcı", "köpek", "sadakat", "duygusal", "gerçek hikaye", "kısa"], pros: ["Çok duygusal", "Gerçek hikaye"], cons: ["Hazırlıksız ağlatır"], spoiler: "Hachi, ölen sahibini 10 yıl boyunca istasyonda bekler." },
    { id: 18, title: "Coco", year: 2017, duration: 105, rating: 8.4, imdb: 8.4, poster: "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=Rvr68uBdZJI", genres: ["Animasyon", "Aile"], overview: "Genç Miguel, Ölüler Diyarı'na yolculuk eder ve ailesinin müzikle olan geçmişini keşfeder.", platforms: ["Disney+"], keywords: ["animasyon", "aile", "müzik", "ağlatıcı", "pixar", "renkli"], pros: ["Görsel şölen", "Müzikler muhteşem", "Duygusal"], cons: ["Çocuklar için ürkütücü olabilir"], spoiler: "Héctor, Miguel'in büyük büyük dedesi çıkar." },
    { id: 19, title: "Ratatouille", year: 2007, duration: 111, rating: 8.1, imdb: 8.1, poster: "https://m.media-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=NgsQ8mVkN8w", genres: ["Animasyon", "Komedi"], overview: "Şef olmayı hayal eden fare Remy, Paris'in en ünlü restoranında kariyerine başlar.", platforms: ["Disney+"], keywords: ["animasyon", "mutlu", "yemek", "paris", "pixar", "ilham verici"], pros: ["Yaratıcı konsept", "Paris atmosferi"], cons: ["Fare mutfakta rahatsız edici olabilir"], spoiler: "Remy eleştirmeni etkiler ve restoran açar." },
    { id: 20, title: "Hangover", year: 2009, duration: 100, rating: 7.7, imdb: 7.7, poster: "https://m.media-amazon.com/images/M/MV5BNGQwZjg5YmItNGZhZi00MmUyLTljNjAtZjlhMjliMjI4NjllXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BNGQwZjg5YmItNGZhZi00MmUyLTljNjAtZjlhMjliMjI4NjllXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=tcdUhdOlz9M", genres: ["Komedi"], overview: "Las Vegas'ta bekarlığa veda sonrası üç arkadaş damat adayını bulmaya çalışır.", platforms: ["Netflix", "HBO Max"], keywords: ["komedi", "parti", "las vegas", "eğlenceli", "çılgın", "arkadaşlık"], pros: ["Çok komik", "Sürpriz dolu"], cons: ["Kaba mizah"], spoiler: "Doug çatıda güneşleniyor, orada unutmuşlar." },
    { id: 21, title: "La La Land", year: 2016, duration: 128, rating: 8.0, imdb: 8.0, poster: "https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=0pdqf4P9MB8", genres: ["Romantik", "Müzik"], overview: "Los Angeles'ta hayallerinin peşinde koşan bir aktris ve caz piyanisti aşık olur.", platforms: ["Netflix"], keywords: ["romantik", "müzikal", "renkli", "hayaller", "bitter-sweet", "ağlatıcı"], pros: ["Müzikler muhteşem", "Görsel şölen"], cons: ["Bitter-sweet son üzücü"], spoiler: "Mia ve Sebastian ayrılır, hayallerine ulaşır ama birlikte değiller." },
    { id: 22, title: "Deadpool", year: 2016, duration: 108, rating: 8.0, imdb: 8.0, poster: "https://m.media-amazon.com/images/M/MV5BYzE5MjY1ZDgtMTkyNC00MTMyLThhMjAtZGI5OTE1NzFlZGJjXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BYzE5MjY1ZDgtMTkyNC00MTMyLThhMjAtZGI5OTE1NzFlZGJjXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=ONHBaC-pfsk", genres: ["Aksiyon", "Komedi"], overview: "Kanser hastası Wade Wilson, deney programıyla ölümsüz anti-kahraman olur.", platforms: ["Disney+"], keywords: ["süper kahraman", "komedi", "aksiyon", "kara mizah", "marvel", "eğlenceli"], pros: ["Ryan Reynolds mükemmel", "Farklı süper kahraman filmi"], cons: ["Çok kara mizah"], spoiler: "Deadpool Ajax'ı öldürür ve Vanessa'yı kurtarır." },
    { id: 23, title: "Get Out", year: 2017, duration: 104, rating: 7.7, imdb: 7.7, poster: "https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=DzfpyUB60YY", genres: ["Korku", "Gerilim"], overview: "Chris, kız arkadaşının ailesiyle tanışmak için gider ama tuhaf şeyler fark eder.", platforms: ["Netflix", "Amazon Prime"], keywords: ["korku", "psikolojik", "gerilim", "twist", "farklı", "ürkütücü"], pros: ["Sosyal yorum güçlü", "Beklenmedik hikaye"], cons: ["Bazıları için rahatsız edici"], spoiler: "Aile siyah insanların bedenlerini ele geçiriyor." },
    { id: 24, title: "Büyük Lebowski", year: 1998, duration: 117, rating: 8.1, imdb: 8.1, poster: "https://m.media-amazon.com/images/M/MV5BMTQ0NjUzMDMyOF5BMl5BanBnXkFtZTgwODA1OTU0MDE@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BMTQ0NjUzMDMyOF5BMl5BanBnXkFtZTgwODA1OTU0MDE@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=cd-go0oBF4Y", genres: ["Komedi", "Suç"], overview: "Tembel Jeff 'Dude' Lebowski, yanlış adamla karıştırılınca tuhaf olaylara karışır.", platforms: ["Netflix", "Amazon Prime"], keywords: ["komedi", "kült", "absürt", "eğlenceli", "bowling", "farklı"], pros: ["Jeff Bridges ikonik", "Kült klasik"], cons: ["Herkes için değil"], spoiler: "Fidye parası havaya uçar, Dude hayatına devam eder." },
    { id: 25, title: "Sessiz Bir Yer", year: 2018, duration: 90, rating: 7.5, imdb: 7.5, poster: "https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=WR7cc5t7tv8", genres: ["Korku", "Bilim Kurgu"], overview: "Sese duyarlı yaratıkların istila ettiği dünyada bir aile hayatta kalmaya çalışır.", platforms: ["Netflix", "Amazon Prime"], keywords: ["korku", "gerilim", "sessiz", "aile", "hayatta kalma", "kısa"], pros: ["Orijinal konsept", "Gerilim mükemmel"], cons: ["Mantık hataları var"], spoiler: "Bebeğin ağlaması yaratıkları çeker ama baba kendini feda eder." },
    { id: 26, title: "Soul", year: 2020, duration: 100, rating: 8.0, imdb: 8.0, poster: "https://m.media-amazon.com/images/M/MV5BZGFmMjM4NTctNzQ0MC00YWE5LWFhNGQtY2I1YjA5OWNhNWMxXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BZGFmMjM4NTctNzQ0MC00YWE5LWFhNGQtY2I1YjA1OWNhNWMxXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=xOsLIpOnXRo", genres: ["Animasyon", "Komedi"], overview: "Caz tutkunu müzik öğretmeni Joe, ölüm ile yaşam arasındaki dünyayı keşfeder.", platforms: ["Disney+"], keywords: ["animasyon", "düşündürücü", "müzik", "yaşam", "pixar", "felsefe"], pros: ["Derin mesajlar", "Görsel muhteşem"], cons: ["Çocuklar için karmaşık"], spoiler: "Joe hayata döner ve anı yaşamayı öğrenir." },
    { id: 27, title: "12 Öfkeli Adam", year: 1957, duration: 96, rating: 9.0, imdb: 9.0, poster: "https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxNTQ1NjUyNDNlXkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxNTQ1NjUyNDNlXkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=TEN-2uTi2c0", genres: ["Dram", "Suç"], overview: "12 jüri üyesi bir cinayet davasında karar vermek zorundadır.", platforms: ["Amazon Prime", "MUBI"], keywords: ["klasik", "düşündürücü", "dram", "adalet", "siyah beyaz", "efsane"], pros: ["Tek odada geçen şaheser", "Oyunculuklar mükemmel"], cons: ["Siyah beyaz herkes için değil"], spoiler: "8 numaralı jüri herkesi ikna eder, sanık beraat eder." },
    { id: 28, title: "Babam ve Oğlum", year: 2005, duration: 108, rating: 8.2, imdb: 8.2, poster: "https://m.media-amazon.com/images/M/MV5BNjA4NTQzOTU4Nl5BMl5BanBnXkFtZTgwNzU0NjQ5MTE@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BNjA4NTQzOTU4Nl5BMl5BanBnXkFtZTgwNzU0NjQ5MTE@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=x8yrXNZ1PsU", genres: ["Dram", "Aile"], overview: "Siyasi olayların gölgesinde bir baba, oğlu ve torunun hikayesi.", platforms: ["BluTV", "Netflix"], keywords: ["türk", "aile", "ağlatıcı", "baba", "duygusal", "klasik"], pros: ["Türk sinemasının en iyilerinden", "Çok duygusal"], cons: ["Hazırlıksız ağlatır"], spoiler: "Sadık ölür, Deniz büyükbabasıyla kalır." },
    { id: 29, title: "Ayla", year: 2017, duration: 125, rating: 8.3, imdb: 8.3, poster: "https://m.media-amazon.com/images/M/MV5BMzk1MzBjZjItN2E2ZS00NWE1LWFmZDUtMjc1ZGU3M2IzMjc2XkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BMzk1MzBjZjItN2E2ZS00NWE1LWFmZDUtMjc1ZGU3M2IzMjc2XkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=IxPHKGqN2eg", genres: ["Dram", "Savaş"], overview: "Kore Savaşı'nda Türk askeri Süleyman, savaş yetimi küçük kızı sahiplenir.", platforms: ["Netflix", "BluTV"], keywords: ["türk", "savaş", "ağlatıcı", "gerçek hikaye", "duygusal", "baba"], pros: ["Gerçek hikaye", "Çok duygusal"], cons: ["Ağır konular"], spoiler: "Süleyman ve Ayla 60 yıl sonra tekrar buluşur." },
    { id: 30, title: "Notebook", year: 2004, duration: 123, rating: 7.8, imdb: 7.8, poster: "https://m.media-amazon.com/images/M/MV5BNzc3Mzg1OGYtZjc3My00Y2NhLTgyOWUtYjRhMmI4OTkwNDg4XkEyXkFqcGc@._V1_SX300.jpg", backdrop: "https://m.media-amazon.com/images/M/MV5BNzc3Mzg1OGYtZjc3My00Y2NhLTgyOWUtYjRhMmI4OTkwNDg4XkEyXkFqcGc@._V1_.jpg", trailer: "https://www.youtube.com/watch?v=yDJIcgtzEYw", genres: ["Romantik", "Dram"], overview: "1940'larda başlayan ve ömür boyu süren tutkulu bir aşk hikayesi.", platforms: ["Netflix", "Amazon Prime"], keywords: ["romantik", "ağlatıcı", "aşk", "klasik", "duygusal", "nostaljik"], pros: ["Romantik klasik", "Ryan Gosling & Rachel McAdams"], cons: ["Çok duygusal"], spoiler: "Noah ve Allie birlikte ölür." }
];

const MOOD_KEYWORDS = {
    sad: ["ağlatıcı", "duygusal", "dram", "hüzünlü", "trajik"],
    happy: ["mutlu", "komedi", "eğlenceli", "renkli", "sevimli"],
    relaxed: ["rahat", "huzurlu", "nostaljik", "animasyon", "aile"],
    excited: ["aksiyon", "heyecan", "gerilim", "epik", "savaş", "süper kahraman"],
    romantic: ["romantik", "aşk", "güzel", "paris", "duygusal"],
    scared: ["korku", "gerilim", "ürkütücü", "paranormal", "psikolojik"],
    thoughtful: ["düşündürücü", "felsefe", "psikolojik", "twist", "gizem"],
    nostalgic: ["nostaljik", "klasik", "retro", "eski"]
};

const SEARCH_MAPPINGS = {
    "ağla": ["ağlatıcı", "duygusal", "trajik"], "hüngür": ["ağlatıcı", "duygusal"], "gül": ["komedi", "eğlenceli", "mutlu"],
    "kork": ["korku", "gerilim", "ürkütücü"], "düşün": ["düşündürücü", "felsefe"], "aşk": ["romantik", "aşk"],
    "aksiyon": ["aksiyon", "savaş"], "komedi": ["komedi", "eğlenceli"], "dram": ["dram", "duygusal"],
    "korku": ["korku", "ürkütücü"], "bilim kurgu": ["bilim kurgu", "uzay"], "animasyon": ["animasyon", "pixar"],
    "twist": ["twist"], "klasik": ["klasik", "efsane"], "türk": ["türk"], "kore": ["kore"], "aile": ["aile", "animasyon"]
};

window.MOVIES = MOVIES;
window.MOOD_KEYWORDS = MOOD_KEYWORDS;
window.SEARCH_MAPPINGS = SEARCH_MAPPINGS;
